/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    NavBase: typeof import('./components/nav/src/NavBase.vue')['default']
    NavItem: typeof import('./components/nav/src/NavItem.vue')['default']
    NavMain: typeof import('./components/nav/src/NavMain.vue')['default']
    NavPopover: typeof import('./components/nav/src/NavPopover.vue')['default']
    NavPopper: typeof import('./components/nav/src/NavPopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
